spring.application.name=uamishop-main

# URLs de los Microservicios (coinciden con los nombres en docker-compose)
catalogo.service.url=http://uamishop-catalogo:8081

ordenes.service.url=http://uamishop-orden:8082

# Configuración de RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Base de datos MySQL (Perfil principal)
spring.datasource.url=jdbc:mysql://mysql:3306/uamishop?useSSL=false&serverTimezone=UTC
spring.datasource.username=uamishop
spring.datasource.password=uamishop
spring.jpa.hibernate.ddl-auto=update